services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # HTTP port
      - "6334:6334"  # gRPC port
    environment:
      - QDRANT__CLUSTER__ENABLED=false
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    volumes:
      - qdrant_data:/qdrant/storage
volumes:
  redis_data:
  qdrant_data: